language: node_js
cache:
  directories:
  - node_modules notifications:
email: false
node_js:
- '7'
- '6'
branches:
  except:
  - /^v\d+\.\d+\.\d+$/
env:
  global:
  - secure: i2lUQ5rG0DL/2fOYMeygPW1+HdXDBhwUQcasTaBChhmHxOjMbdt4al+7FzTCzYzPfwiJsx8yDPpaozeZKguLjS+0sUbvwx/dTiaKgd5NA1jiqQ4X6/K1CFWB+fyEnMjPtANczdA1vgSlBFzJMO0noW5dVUJ4UenV8b+CAZvfs9yONobcL2idNITokBr50r63lnf/zQibXJTCL/Gu2RDfUW8jqHgxfv/ywXOKlWptPY2uWEJYXecdt+9t+5Wvb4deG+mswwtVsosC7GgvzmV8M6txioBOcprSR4dfkFPJq3pXR//N1lQHvlhf6NWwGqAhjo6Z3waGpIbEsRLQM8qzfvf26jacem/HxLkdjw+Dm8yccoyFdQ0QppxKs/P2j3rNZU6rmDVIq3cG7wbiIbrWekuhFuuNBy+mS/jwwHD71s3rQfq6a9iZzF8L+XflJuL6RJ5QMXMOenV6LumBLLJdK8SzU1JrGfLWuUQREU37dNaCXCBHTEPPUiRb8SsvKc8yxGI6kgLdcsAoED5UgLFU0VEVp5nHNiXa8QkrS23awVU+aR9u/HO6xH9vEjh6gGi/GceWctzJSejgnIhXJh1mx4rVuTeeGOf7PE6fduoQw2VPmahuWsSjPEuEclXa+KdXO/xMFPnpfquDaX5mkR8K0TWZb1616S/cP/Yz5lYCyO0=
