language: node_js
cache:
  directories:
  - node_modules notifications:
email: false
node_js:
- '7'
- '6'
branches:
  except:
  - /^v\d+\.\d+\.\d+$/
env:
  global:
  - secure: bkmMC/qgOPouNa/4O3aCbOerXMOBf+Z6oDfYVpNpMcYiZDWLYIF9OcXdNyJ4wuzrt6dLQh1kcgcPn+qhJNSp2JfZSwJuzApL3ZFhZH9CwQnawNt26EUeJDudaZqjOXeFPBKeWe2DB/v7sfEtu6e0FAYfBaGM5Tf4XDkUMq5VdiTtTQH/3g+xmgnqdb7PF5ilfKNmYleZxsjCD4LZsYew+cyOW72MfjhV0t9UXAIalXk1Oj0g7A35AKeGrjBf9OBugv9Qd7rhVzWUH28umY0uyVdFydd4AhxeG+1p41bUnUa6EYkf/GJ6BdCzMqhg2hWGEMCl5huZ+fcCaARs8EOS69NphEK4df2jVysY5jG5Q7r+lg7W+J30H/n/9azg/aZr2TwtBukKyXbiwRjTODG+Xg1LFwZSgY96ffygSwWuzE6SNS0WQTMpykwO/9Bakb16dQF8YBZR+dIyIchpz48+aTj9kMqPtrSOSzDHg9M9TWPFuLi2rWLmaAMjXu+KyECiyPyOESmiiYhuMcpOrV5URwH/V+dyoTpEuPbn/y/DzGkrur8cYol/qnPsZ6yCJWfoTJ6nAVIKi/J/+90kHH2J/kI9tkqcpZsy05sycrN81oMw4lu4KFOkMaFW64H4KJVBFWGWQCvq9em2rR8s9aizrrNSliqrMxlYchHBXY6vMV4=
  - secure: i2lUQ5rG0DL/2fOYMeygPW1+HdXDBhwUQcasTaBChhmHxOjMbdt4al+7FzTCzYzPfwiJsx8yDPpaozeZKguLjS+0sUbvwx/dTiaKgd5NA1jiqQ4X6/K1CFWB+fyEnMjPtANczdA1vgSlBFzJMO0noW5dVUJ4UenV8b+CAZvfs9yONobcL2idNITokBr50r63lnf/zQibXJTCL/Gu2RDfUW8jqHgxfv/ywXOKlWptPY2uWEJYXecdt+9t+5Wvb4deG+mswwtVsosC7GgvzmV8M6txioBOcprSR4dfkFPJq3pXR//N1lQHvlhf6NWwGqAhjo6Z3waGpIbEsRLQM8qzfvf26jacem/HxLkdjw+Dm8yccoyFdQ0QppxKs/P2j3rNZU6rmDVIq3cG7wbiIbrWekuhFuuNBy+mS/jwwHD71s3rQfq6a9iZzF8L+XflJuL6RJ5QMXMOenV6LumBLLJdK8SzU1JrGfLWuUQREU37dNaCXCBHTEPPUiRb8SsvKc8yxGI6kgLdcsAoED5UgLFU0VEVp5nHNiXa8QkrS23awVU+aR9u/HO6xH9vEjh6gGi/GceWctzJSejgnIhXJh1mx4rVuTeeGOf7PE6fduoQw2VPmahuWsSjPEuEclXa+KdXO/xMFPnpfquDaX5mkR8K0TWZb1616S/cP/Yz5lYCyO0=
